add forbidden slug option
spatie/laravel-sluggable pull request #239
Opened 2022-11-01 14:01 UTC by hotsaucejake

This PR allows the ability to specify forbidden slugs that should NOT be generated.  My use case was to avoid route collision.  I have models with soft deletes and setup routes to handle various tasks like:

```
model/{model}
model/trashed // index of all soft deleted models
```

What if the user creates a model that generates one of these slugs?  They won't be able access their model or perform these tasks.  There are probably more use cases than this one.

```php
class Page extends Model
{
        HasSlug;

        public function getSlugOptions(): SlugOptions
        {
            return parent::getSlugOptions()
                ->forbiddenSlugs(['annihilate', 'restore']);
        }
}
```

2022-11-01 14:08 UTC, hotsaucejake commented
This will also account for unspecified forbidden slugs or an empty array:

```php
public function getSlugOptions(): SlugOptions
{
        return parent::getSlugOptions()
            ->forbiddenSlugs();
}
```

```php
public function getSlugOptions(): SlugOptions
{
        return parent::getSlugOptions()
            ->forbiddenSlugs([]);
}
```

2022-11-01 15:33 UTC, hotsaucejake commented
Had to include the composer file because of failed checks

2022-11-01 16:14 UTC, hotsaucejake commented
@freekmurze there is a fix to the checks now - it was a composer update to allow for the plugin in the config section

2022-11-02 13:04 UTC, freekmurze requested changes

2022-11-02 13:04 UTC, freekmurze commented on src/HasSlug.php
> +        while ($this->otherRecordExistsWithSlug($slug) || $slug === '' || in_array($slug, $this->slugOptions->forbiddenSlugs)) {
This is unreadable. Could you extract this to a function with a good name? Also try to avoid `||` in there.

2022-11-06 18:09 UTC, freekmurze commented
Thanks, but after thinking things through, I'm going to pass on this because I want to keep the package as simple as possible.

People that need this behaviour can override the `generateNonUniqueSlug()` method.

2022-11-06 18:09 UTC, closed without merging

2022-11-07 01:38 UTC, hotsaucejake commented
@freekmurze this is the same comment left on this pull request: https://github.com/spatie/laravel-sluggable/pull/242 that you just closed.  Is it for the same reason?

This particular pull request allows a user to define a list of slugs that should NOT be generated.  

I'm not sure how overriding the the `generateNonUniqueSlug()` method applies here or one would go about not allowing certain slugs to be generated.  Only the `HasTranslatableSlug` trait contains this method.

2022-11-07 08:55 UTC, freekmurze commented
I think you could adapt [this method](https://github.com/spatie/laravel-sluggable/blob/7435973fadf5d2b77ba2b1d2c4b2d62cd5162c8a/src/HasSlug.php#L90-L98) to see if `$this->getSlugSourceString()` returns a forbidden slug source.

2023-06-27 11:25 UTC, fabiomlferreira commented
@freekmurze I believe it would be beneficial to revisit the potential addition of a reserved words feature in the sluggable plugin. It's common practice in many sluggable solutions to provide an easy mechanism for adding reserved words, and I think integrating this feature would significantly enhance the utility and user experience of our package. It's a feature that could provide substantial value to many users.